import {
    MATERIAL_AMBER_600,
    MATERIAL_BLUE_600,
    MATERIAL_CYAN_600,
    MATERIAL_DEEP_ORANGE_600,
    MATERIAL_DEEP_PURPLE_600,
    MATERIAL_GREEN_600,
    MATERIAL_INDIGO_600,
    MATERIAL_LIGHT_BLUE_600,
    MATERIAL_LIGHT_GREEN_600,
    MATERIAL_LIME_600,
    MATERIAL_ORANGE_600,
    MATERIAL_PINK_600,
    MATERIAL_PURPLE_600,
    MATERIAL_RED_600,
    MATERIAL_TEAL_600,
    MATERIAL_YELLOW_600
} from "./material-colors";

export const ACCENT_RED = "red";
export const ACCENT_PINK = "pink";
export const ACCENT_PURPLE = "purple";
export const ACCENT_DEEP_PURPLE = "deep-purple";
export const ACCENT_INDIGO = "indigo";
export const ACCENT_BLUE = "blue";
export const ACCENT_LIGHT_BLUE = "light-blue";
export const ACCENT_CYAN = "cyan";
export const ACCENT_TEAL = "teal";
export const ACCENT_GREEN = "green";
export const ACCENT_LIGHT_GREEN = "light-green";
export const ACCENT_LIME = "lime";
export const ACCENT_YELLOW = "yellow";
export const ACCENT_AMBER = "amber";
export const ACCENT_ORANGE = "orange";
export const ACCENT_DEEP_ORANGE = "deep-orange";

export const ACCENT_RED_COLOR = MATERIAL_RED_600;
export const ACCENT_PINK_COLOR = MATERIAL_PINK_600;
export const ACCENT_PURPLE_COLOR = MATERIAL_PURPLE_600;
export const ACCENT_DEEP_PURPLE_COLOR = MATERIAL_DEEP_PURPLE_600;
export const ACCENT_INDIGO_COLOR = MATERIAL_INDIGO_600;
export const ACCENT_BLUE_COLOR = MATERIAL_BLUE_600;
export const ACCENT_LIGHT_BLUE_COLOR = MATERIAL_LIGHT_BLUE_600;
export const ACCENT_CYAN_COLOR = MATERIAL_CYAN_600;
export const ACCENT_TEAL_COLOR = MATERIAL_TEAL_600;
export const ACCENT_GREEN_COLOR = MATERIAL_GREEN_600;
export const ACCENT_LIGHT_GREEN_COLOR = MATERIAL_LIGHT_GREEN_600;
export const ACCENT_LIME_COLOR = MATERIAL_LIME_600;
export const ACCENT_YELLOW_COLOR = MATERIAL_YELLOW_600;
export const ACCENT_AMBER_COLOR = MATERIAL_AMBER_600;
export const ACCENT_ORANGE_COLOR = MATERIAL_ORANGE_600;
export const ACCENT_DEEP_ORANGE_COLOR = MATERIAL_DEEP_ORANGE_600;

export const ACCENTS = [
    ACCENT_RED,
    ACCENT_PINK,
    ACCENT_PURPLE,
    ACCENT_DEEP_PURPLE,
    ACCENT_INDIGO,
    ACCENT_BLUE,
    ACCENT_LIGHT_BLUE,
    ACCENT_CYAN,
    ACCENT_TEAL,
    ACCENT_GREEN,
    ACCENT_LIGHT_GREEN,
    ACCENT_LIME,
    ACCENT_YELLOW,
    ACCENT_AMBER,
    ACCENT_ORANGE,
    ACCENT_DEEP_ORANGE
];

export const ACCENT_COLORS = {
    [ACCENT_RED]: ACCENT_RED_COLOR,
    [ACCENT_PINK]: ACCENT_PINK_COLOR,
    [ACCENT_PURPLE]: ACCENT_PURPLE_COLOR,
    [ACCENT_DEEP_PURPLE]: ACCENT_DEEP_PURPLE_COLOR,
    [ACCENT_INDIGO]: ACCENT_INDIGO_COLOR,
    [ACCENT_BLUE]: ACCENT_BLUE_COLOR,
    [ACCENT_LIGHT_BLUE]: ACCENT_LIGHT_BLUE_COLOR,
    [ACCENT_CYAN]: ACCENT_CYAN_COLOR,
    [ACCENT_TEAL]: ACCENT_TEAL_COLOR,
    [ACCENT_GREEN]: ACCENT_GREEN_COLOR,
    [ACCENT_LIGHT_GREEN]: ACCENT_LIGHT_GREEN_COLOR,
    [ACCENT_LIME]: ACCENT_LIME_COLOR,
    [ACCENT_YELLOW]: ACCENT_YELLOW_COLOR,
    [ACCENT_AMBER]: ACCENT_AMBER_COLOR,
    [ACCENT_ORANGE]: ACCENT_ORANGE_COLOR,
    [ACCENT_DEEP_ORANGE]: ACCENT_DEEP_ORANGE_COLOR
};
