export const COUNTRIES = [
    {
        name: "Afghanistan",
        phoneCode: "+93",
        id: "AF"
    }, {
        name: "Aland Islands",
        phoneCode: "+358",
        id: "AX"
    }, {
        name: "Albania",
        phoneCode: "+355",
        id: "AL"
    }, {
        name: "Algeria",
        phoneCode: "+213",
        id: "DZ"
    }, {
        name: "American Samoa",
        phoneCode: "+1684",
        id: "AS"
    }, {
        name: "Andorra",
        phoneCode: "+376",
        id: "AD"
    }, {
        name: "Angola",
        phoneCode: "+244",
        id: "AO"
    }, {
        name: "Anguilla",
        phoneCode: "+1264",
        id: "AI"
    }, {
        name: "Antarctica",
        phoneCode: "+672",
        id: "AQ"
    }, {
        name: "Antigua and Barbuda",
        phoneCode: "+1268",
        id: "AG"
    }, {
        name: "Argentina",
        phoneCode: "+54",
        id: "AR"
    }, {
        name: "Armenia",
        phoneCode: "+374",
        id: "AM"
    }, {
        name: "Aruba",
        phoneCode: "+297",
        id: "AW"
    }, {
        name: "Australia",
        phoneCode: "+61",
        id: "AU"
    }, {
        name: "Austria",
        phoneCode: "+43",
        id: "AT"
    }, {
        name: "Azerbaijan",
        phoneCode: "+994",
        id: "AZ"
    }, {
        name: "Bahamas",
        phoneCode: "+1242",
        id: "BS"
    }, {
        name: "Bahrain",
        phoneCode: "+973",
        id: "BH"
    }, {
        name: "Bangladesh",
        phoneCode: "+880",
        id: "BD"
    }, {
        name: "Barbados",
        phoneCode: "+1246",
        id: "BB"
    }, {
        name: "Belarus",
        phoneCode: "+375",
        id: "BY"
    }, {
        name: "Belgium",
        phoneCode: "+32",
        id: "BE"
    }, {
        name: "Belize",
        phoneCode: "+501",
        id: "BZ"
    }, {
        name: "Benin",
        phoneCode: "+229",
        id: "BJ"
    }, {
        name: "Bermuda",
        phoneCode: "+1441",
        id: "BM"
    }, {
        name: "Bhutan",
        phoneCode: "+975",
        id: "BT"
    }, {
        name: "Bolivia, Plurinational State of",
        phoneCode: "+591",
        id: "BO"
    }, {
        name: "Bosnia and Herzegovina",
        phoneCode: "+387",
        id: "BA"
    }, {
        name: "Botswana",
        phoneCode: "+267",
        id: "BW"
    }, {
        name: "Brazil",
        phoneCode: "+55",
        id: "BR"
    }, {
        name: "British Indian Ocean Territory",
        phoneCode: "+246",
        id: "IO"
    }, {
        name: "Brunei Darussalam",
        phoneCode: "+673",
        id: "BN"
    }, {
        name: "Bulgaria",
        phoneCode: "+359",
        id: "BG"
    }, {
        name: "Burkina Faso",
        phoneCode: "+226",
        id: "BF"
    }, {
        name: "Burundi",
        phoneCode: "+257",
        id: "BI"
    }, {
        name: "Cambodia",
        phoneCode: "+855",
        id: "KH"
    }, {
        name: "Cameroon",
        phoneCode: "+237",
        id: "CM"
    }, {
        name: "Canada",
        phoneCode: "+1",
        id: "CA"
    }, {
        name: "Cape Verde",
        phoneCode: "+238",
        id: "CV"
    }, {
        name: "Cayman Islands",
        phoneCode: "+ 345",
        id: "KY"
    }, {
        name: "Central African Republic",
        phoneCode: "+236",
        id: "CF"
    }, {
        name: "Chad",
        phoneCode: "+235",
        id: "TD"
    }, {
        name: "Chile",
        phoneCode: "+56",
        id: "CL"
    }, {
        name: "China",
        phoneCode: "+86",
        id: "CN"
    }, {
        name: "Christmas Island",
        phoneCode: "+61",
        id: "CX"
    }, {
        name: "Cocos (Keeling) Islands",
        phoneCode: "+61",
        id: "CC"
    }, {
        name: "Colombia",
        phoneCode: "+57",
        id: "CO"
    }, {
        name: "Comoros",
        phoneCode: "+269",
        id: "KM"
    }, {
        name: "Congo",
        phoneCode: "+242",
        id: "CG"
    }, {
        name: "Congo, The Democratic Republic of the Congo",
        phoneCode: "+243",
        id: "CD"
    }, {
        name: "Cook Islands",
        phoneCode: "+682",
        id: "CK"
    }, {
        name: "Costa Rica",
        phoneCode: "+506",
        id: "CR"
    }, {
        name: "Cote d'Ivoire",
        phoneCode: "+225",
        id: "CI"
    }, {
        name: "Croatia",
        phoneCode: "+385",
        id: "HR"
    }, {
        name: "Cuba",
        phoneCode: "+53",
        id: "CU"
    }, {
        name: "Cyprus",
        phoneCode: "+357",
        id: "CY"
    }, {
        name: "Czech Republic",
        phoneCode: "+420",
        id: "CZ"
    }, {
        name: "Denmark",
        phoneCode: "+45",
        id: "DK"
    }, {
        name: "Djibouti",
        phoneCode: "+253",
        id: "DJ"
    }, {
        name: "Dominica",
        phoneCode: "+1767",
        id: "DM"
    }, {
        name: "Dominican Republic",
        phoneCode: "+1849",
        id: "DO"
    }, {
        name: "Ecuador",
        phoneCode: "+593",
        id: "EC"
    }, {
        name: "Egypt",
        phoneCode: "+20",
        id: "EG"
    }, {
        name: "El Salvador",
        phoneCode: "+503",
        id: "SV"
    }, {
        name: "Equatorial Guinea",
        phoneCode: "+240",
        id: "GQ"
    }, {
        name: "Eritrea",
        phoneCode: "+291",
        id: "ER"
    }, {
        name: "Estonia",
        phoneCode: "+372",
        id: "EE"
    }, {
        name: "Ethiopia",
        phoneCode: "+251",
        id: "ET"
    }, {
        name: "Falkland Islands (Malvinas)",
        phoneCode: "+500",
        id: "FK"
    }, {
        name: "Faroe Islands",
        phoneCode: "+298",
        id: "FO"
    }, {
        name: "Fiji",
        phoneCode: "+679",
        id: "FJ"
    }, {
        name: "Finland",
        phoneCode: "+358",
        id: "FI"
    }, {
        name: "France",
        phoneCode: "+33",
        id: "FR"
    }, {
        name: "French Guiana",
        phoneCode: "+594",
        id: "GF"
    }, {
        name: "French Polynesia",
        phoneCode: "+689",
        id: "PF"
    }, {
        name: "Gabon",
        phoneCode: "+241",
        id: "GA"
    }, {
        name: "Gambia",
        phoneCode: "+220",
        id: "GM"
    }, {
        name: "Georgia",
        phoneCode: "+995",
        id: "GE"
    }, {
        name: "Germany",
        phoneCode: "+49",
        id: "DE"
    }, {
        name: "Ghana",
        phoneCode: "+233",
        id: "GH"
    }, {
        name: "Gibraltar",
        phoneCode: "+350",
        id: "GI"
    }, {
        name: "Greece",
        phoneCode: "+30",
        id: "GR"
    }, {
        name: "Greenland",
        phoneCode: "+299",
        id: "GL"
    }, {
        name: "Grenada",
        phoneCode: "+1473",
        id: "GD"
    }, {
        name: "Guadeloupe",
        phoneCode: "+590",
        id: "GP"
    }, {
        name: "Guam",
        phoneCode: "+1671",
        id: "GU"
    }, {
        name: "Guatemala",
        phoneCode: "+502",
        id: "GT"
    }, {
        name: "Guernsey",
        phoneCode: "+44",
        id: "GG"
    }, {
        name: "Guinea",
        phoneCode: "+224",
        id: "GN"
    }, {
        name: "Guinea-Bissau",
        phoneCode: "+245",
        id: "GW"
    }, {
        name: "Guyana",
        phoneCode: "+595",
        id: "GY"
    }, {
        name: "Haiti",
        phoneCode: "+509",
        id: "HT"
    }, {
        name: "Holy See (Vatican City State)",
        phoneCode: "+379",
        id: "VA"
    }, {
        name: "Honduras",
        phoneCode: "+504",
        id: "HN"
    }, {
        name: "Hong Kong",
        phoneCode: "+852",
        id: "HK"
    }, {
        name: "Hungary",
        phoneCode: "+36",
        id: "HU"
    }, {
        name: "Iceland",
        phoneCode: "+354",
        id: "IS"
    }, {
        name: "India",
        phoneCode: "+91",
        id: "IN"
    }, {
        name: "Indonesia",
        phoneCode: "+62",
        id: "ID"
    }, {
        name: "Iran, Islamic Republic of Persian Gulf",
        phoneCode: "+98",
        id: "IR"
    }, {
        name: "Iraq",
        phoneCode: "+964",
        id: "IQ"
    }, {
        name: "Ireland",
        phoneCode: "+353",
        id: "IE"
    }, {
        name: "Isle of Man",
        phoneCode: "+44",
        id: "IM"
    }, {
        name: "Israel",
        phoneCode: "+972",
        id: "IL"
    }, {
        name: "Italy",
        phoneCode: "+39",
        id: "IT"
    }, {
        name: "Jamaica",
        phoneCode: "+1876",
        id: "JM"
    }, {
        name: "Japan",
        phoneCode: "+81",
        id: "JP"
    }, {
        name: "Jersey",
        phoneCode: "+44",
        id: "JE"
    }, {
        name: "Jordan",
        phoneCode: "+962",
        id: "JO"
    }, {
        name: "Kazakhstan",
        phoneCode: "+77",
        id: "KZ"
    }, {
        name: "Kenya",
        phoneCode: "+254",
        id: "KE"
    }, {
        name: "Kiribati",
        phoneCode: "+686",
        id: "KI"
    }, {
        name: "Korea, Democratic People's Republic of Korea",
        phoneCode: "+850",
        id: "KP"
    }, {
        name: "Korea, Republic of South Korea",
        phoneCode: "+82",
        id: "KR"
    }, {
        name: "Kuwait",
        phoneCode: "+965",
        id: "KW"
    }, {
        name: "Kyrgyzstan",
        phoneCode: "+996",
        id: "KG"
    }, {
        name: "Laos",
        phoneCode: "+856",
        id: "LA"
    }, {
        name: "Latvia",
        phoneCode: "+371",
        id: "LV"
    }, {
        name: "Lebanon",
        phoneCode: "+961",
        id: "LB"
    }, {
        name: "Lesotho",
        phoneCode: "+266",
        id: "LS"
    }, {
        name: "Liberia",
        phoneCode: "+231",
        id: "LR"
    }, {
        name: "Libyan Arab Jamahiriya",
        phoneCode: "+218",
        id: "LY"
    }, {
        name: "Liechtenstein",
        phoneCode: "+423",
        id: "LI"
    }, {
        name: "Lithuania",
        phoneCode: "+370",
        id: "LT"
    }, {
        name: "Luxembourg",
        phoneCode: "+352",
        id: "LU"
    }, {
        name: "Macao",
        phoneCode: "+853",
        id: "MO"
    }, {
        name: "Macedonia",
        phoneCode: "+389",
        id: "MK"
    }, {
        name: "Madagascar",
        phoneCode: "+261",
        id: "MG"
    }, {
        name: "Malawi",
        phoneCode: "+265",
        id: "MW"
    }, {
        name: "Malaysia",
        phoneCode: "+60",
        id: "MY"
    }, {
        name: "Maldives",
        phoneCode: "+960",
        id: "MV"
    }, {
        name: "Mali",
        phoneCode: "+223",
        id: "ML"
    }, {
        name: "Malta",
        phoneCode: "+356",
        id: "MT"
    }, {
        name: "Marshall Islands",
        phoneCode: "+692",
        id: "MH"
    }, {
        name: "Martinique",
        phoneCode: "+596",
        id: "MQ"
    }, {
        name: "Mauritania",
        phoneCode: "+222",
        id: "MR"
    }, {
        name: "Mauritius",
        phoneCode: "+230",
        id: "MU"
    }, {
        name: "Mayotte",
        phoneCode: "+262",
        id: "YT"
    }, {
        name: "Mexico",
        phoneCode: "+52",
        id: "MX"
    }, {
        name: "Micronesia, Federated States of Micronesia",
        phoneCode: "+691",
        id: "FM"
    }, {
        name: "Moldova",
        phoneCode: "+373",
        id: "MD"
    }, {
        name: "Monaco",
        phoneCode: "+377",
        id: "MC"
    }, {
        name: "Mongolia",
        phoneCode: "+976",
        id: "MN"
    }, {
        name: "Montenegro",
        phoneCode: "+382",
        id: "ME"
    }, {
        name: "Montserrat",
        phoneCode: "+1664",
        id: "MS"
    }, {
        name: "Morocco",
        phoneCode: "+212",
        id: "MA"
    }, {
        name: "Mozambique",
        phoneCode: "+258",
        id: "MZ"
    }, {
        name: "Myanmar",
        phoneCode: "+95",
        id: "MM"
    }, {
        name: "Namibia",
        phoneCode: "+264",
        id: "NA"
    }, {
        name: "Nauru",
        phoneCode: "+674",
        id: "NR"
    }, {
        name: "Nepal",
        phoneCode: "+977",
        id: "NP"
    }, {
        name: "Netherlands",
        phoneCode: "+31",
        id: "NL"
    }, {
        name: "Netherlands Antilles",
        phoneCode: "+599",
        id: "AN"
    }, {
        name: "New Caledonia",
        phoneCode: "+687",
        id: "NC"
    }, {
        name: "New Zealand",
        phoneCode: "+64",
        id: "NZ"
    }, {
        name: "Nicaragua",
        phoneCode: "+505",
        id: "NI"
    }, {
        name: "Niger",
        phoneCode: "+227",
        id: "NE"
    }, {
        name: "Nigeria",
        phoneCode: "+234",
        id: "NG"
    }, {
        name: "Niue",
        phoneCode: "+683",
        id: "NU"
    }, {
        name: "Norfolk Island",
        phoneCode: "+672",
        id: "NF"
    }, {
        name: "Northern Mariana Islands",
        phoneCode: "+1670",
        id: "MP"
    }, {
        name: "Norway",
        phoneCode: "+47",
        id: "NO"
    }, {
        name: "Oman",
        phoneCode: "+968",
        id: "OM"
    }, {
        name: "Pakistan",
        phoneCode: "+92",
        id: "PK"
    }, {
        name: "Palau",
        phoneCode: "+680",
        id: "PW"
    }, {
        name: "Palestinian Territory, Occupied",
        phoneCode: "+970",
        id: "PS"
    }, {
        name: "Panama",
        phoneCode: "+507",
        id: "PA"
    }, {
        name: "Papua New Guinea",
        phoneCode: "+675",
        id: "PG"
    }, {
        name: "Paraguay",
        phoneCode: "+595",
        id: "PY"
    }, {
        name: "Peru",
        phoneCode: "+51",
        id: "PE"
    }, {
        name: "Philippines",
        phoneCode: "+63",
        id: "PH"
    }, {
        name: "Pitcairn",
        phoneCode: "+872",
        id: "PN"
    }, {
        name: "Poland",
        phoneCode: "+48",
        id: "PL"
    }, {
        name: "Portugal",
        phoneCode: "+351",
        id: "PT"
    }, {
        name: "Puerto Rico",
        phoneCode: "+1939",
        id: "PR"
    }, {
        name: "Qatar",
        phoneCode: "+974",
        id: "QA"
    }, {
        name: "Romania",
        phoneCode: "+40",
        id: "RO"
    }, {
        name: "Russia",
        phoneCode: "+7",
        id: "RU"
    }, {
        name: "Rwanda",
        phoneCode: "+250",
        id: "RW"
    }, {
        name: "Reunion",
        phoneCode: "+262",
        id: "RE"
    }, {
        name: "Saint Barthelemy",
        phoneCode: "+590",
        id: "BL"
    }, {
        name: "Saint Helena, Ascension and Tristan Da Cunha",
        phoneCode: "+290",
        id: "SH"
    }, {
        name: "Saint Kitts and Nevis",
        phoneCode: "+1869",
        id: "KN"
    }, {
        name: "Saint Lucia",
        phoneCode: "+1758",
        id: "LC"
    }, {
        name: "Saint Martin",
        phoneCode: "+590",
        id: "MF"
    }, {
        name: "Saint Pierre and Miquelon",
        phoneCode: "+508",
        id: "PM"
    }, {
        name: "Saint Vincent and the Grenadines",
        phoneCode: "+1784",
        id: "VC"
    }, {
        name: "Samoa",
        phoneCode: "+685",
        id: "WS"
    }, {
        name: "San Marino",
        phoneCode: "+378",
        id: "SM"
    }, {
        name: "Sao Tome and Principe",
        phoneCode: "+239",
        id: "ST"
    }, {
        name: "Saudi Arabia",
        phoneCode: "+966",
        id: "SA"
    }, {
        name: "Senegal",
        phoneCode: "+221",
        id: "SN"
    }, {
        name: "Serbia",
        phoneCode: "+381",
        id: "RS"
    }, {
        name: "Seychelles",
        phoneCode: "+248",
        id: "SC"
    }, {
        name: "Sierra Leone",
        phoneCode: "+232",
        id: "SL"
    }, {
        name: "Singapore",
        phoneCode: "+65",
        id: "SG"
    }, {
        name: "Slovakia",
        phoneCode: "+421",
        id: "SK"
    }, {
        name: "Slovenia",
        phoneCode: "+386",
        id: "SI"
    }, {
        name: "Solomon Islands",
        phoneCode: "+677",
        id: "SB"
    }, {
        name: "Somalia",
        phoneCode: "+252",
        id: "SO"
    }, {
        name: "South Africa",
        phoneCode: "+27",
        id: "ZA"
    }, {
        name: "South Sudan",
        phoneCode: "+211",
        id: "SS"
    }, {
        name: "South Georgia and the South Sandwich Islands",
        phoneCode: "+500",
        id: "GS"
    }, {
        name: "Spain",
        phoneCode: "+34",
        id: "ES"
    }, {
        name: "Sri Lanka",
        phoneCode: "+94",
        id: "LK"
    }, {
        name: "Sudan",
        phoneCode: "+249",
        id: "SD"
    }, {
        name: "Suriname",
        phoneCode: "+597",
        id: "SR"
    }, {
        name: "Svalbard and Jan Mayen",
        phoneCode: "+47",
        id: "SJ"
    }, {
        name: "Swaziland",
        phoneCode: "+268",
        id: "SZ"
    }, {
        name: "Sweden",
        phoneCode: "+46",
        id: "SE"
    }, {
        name: "Switzerland",
        phoneCode: "+41",
        id: "CH"
    }, {
        name: "Syrian Arab Republic",
        phoneCode: "+963",
        id: "SY"
    }, {
        name: "Taiwan",
        phoneCode: "+886",
        id: "TW"
    }, {
        name: "Tajikistan",
        phoneCode: "+992",
        id: "TJ"
    }, {
        name: "Tanzania, United Republic of Tanzania",
        phoneCode: "+255",
        id: "TZ"
    }, {
        name: "Thailand",
        phoneCode: "+66",
        id: "TH"
    }, {
        name: "Timor-Leste",
        phoneCode: "+670",
        id: "TL"
    }, {
        name: "Togo",
        phoneCode: "+228",
        id: "TG"
    }, {
        name: "Tokelau",
        phoneCode: "+690",
        id: "TK"
    }, {
        name: "Tonga",
        phoneCode: "+676",
        id: "TO"
    }, {
        name: "Trinidad and Tobago",
        phoneCode: "+1868",
        id: "TT"
    }, {
        name: "Tunisia",
        phoneCode: "+216",
        id: "TN"
    }, {
        name: "Turkey",
        phoneCode: "+90",
        id: "TR"
    }, {
        name: "Turkmenistan",
        phoneCode: "+993",
        id: "TM"
    }, {
        name: "Turks and Caicos Islands",
        phoneCode: "+1649",
        id: "TC"
    }, {
        name: "Tuvalu",
        phoneCode: "+688",
        id: "TV"
    }, {
        name: "Uganda",
        phoneCode: "+256",
        id: "UG"
    }, {
        name: "Ukraine",
        phoneCode: "+380",
        id: "UA"
    }, {
        name: "United Arab Emirates",
        phoneCode: "+971",
        id: "AE"
    }, {
        name: "United Kingdom",
        phoneCode: "+44",
        id: "GB"
    }, {
        name: "United States",
        phoneCode: "+1",
        id: "US"
    }, {
        name: "Uruguay",
        phoneCode: "+598",
        id: "UY"
    }, {
        name: "Uzbekistan",
        phoneCode: "+998",
        id: "UZ"
    }, {
        name: "Vanuatu",
        phoneCode: "+678",
        id: "VU"
    }, {
        name: "Venezuela, Bolivarian Republic of Venezuela",
        phoneCode: "+58",
        id: "VE"
    }, {
        name: "Vietnam",
        phoneCode: "+84",
        id: "VN"
    }, {
        name: "Virgin Islands, British",
        phoneCode: "+1284",
        id: "VG"
    }, {
        name: "Virgin Islands, U.S.",
        phoneCode: "+1340",
        id: "VI"
    }, {
        name: "Wallis and Futuna",
        phoneCode: "+681",
        id: "WF"
    }, {
        name: "Yemen",
        phoneCode: "+967",
        id: "YE"
    }, {
        name: "Zambia",
        phoneCode: "+260",
        id: "ZM"
    }, {
        name: "Zimbabwe",
        phoneCode: "+263",
        id: "ZW"
    }
];
